dependencies:
- name: entando-k8s-controller-coordinator
  repository: http://jenkins-x-chartmuseum:8080
  version: 6.3.7
- alias: expose
  name: exposecontroller
  repository: https://jenkins-x-charts.github.io/v2
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: https://jenkins-x-charts.github.io/v2
  version: 2.3.118
- name: octo-easyclaim-mock
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.21
- name: octo-easyclaim-server
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.42
